openapi: 3.0.1
info:
  title: api-simulador-interessos
  description: Servei que realitza la simulació del calculo d'interès a partir de la data d'inici, data de finalització, tipus d'interès i l'import.
  contact:
    name: Pablo Rábago
    email: prabago@minsait.com
  version: v1
servers:
 -
  url: /
security:
 -
  default: []
tags:
 -
  name: calcular
paths:
  /recalcularCalcul:
    post:
      tags:
       - calcular
      summary: calcular interessos
      description: Mètode que realitza la simulació del calculo d'interès a partir de la data d'inici, data de finalització, tipus d'interès i l'import.
      operationId: post-recalcularCalcul
      parameters:
       -
        name: activityid
        in: header
        description: |
          Identificador únic de la petició
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
          example: 469f40c5-450e-4e02-910c-64e850125d6d
      requestBody:
        content:
          application/json:
            schema:
              required:
               - Envelope
              type: object
              properties:
                Envelope:
                  required:
                   - Body
                   - Header
                  type: object
                  properties:
                    Header:
                      type: string
                    Body:
                      required:
                       - recalcularCalcul
                      type: object
                      properties:
                        recalcularCalcul:
                          required:
                           - dataFi
                           - dataInici
                           - import
                           - tipusInteres
                          type: object
                          properties:
                            dataFi:
                              minLength: 1
                              type: string
                            dataInici:
                              minLength: 1
                              type: string
                            import:
                              type: number
                            tipusInteres:
                              minLength: 1
                              type: string
              x-examples:
                example-1:
                  Envelope:
                    Header: ""
                    Body:
                      recalcularCalcul:
                        dataFi: 23/06/2021
                        dataInici: 23/05/2021
                        import: 1000
                        tipusInteres: D
            examples:
              Request:
                value:
                  Envelope:
                    Header: ""
                    Body:
                      recalcularCalcul:
                        dataFi: 23/06/2021
                        dataInici: 23/05/2021
                        import: 1000
                        tipusInteres: D
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                required:
                 - Envelope
                type: object
                properties:
                  Envelope:
                    required:
                     - Body
                    type: object
                    properties:
                      Body:
                        required:
                         - recalcularCalculResponse
                        type: object
                        properties:
                          recalcularCalculResponse:
                            required:
                             - codError
                             - interessosExt
                            type: object
                            properties:
                              codError:
                                type: number
                              interessosExt:
                                required:
                                 - GTH06_InteressosExt
                                type: object
                                properties:
                                  GTH06_InteressosExt:
                                    required:
                                     - dataFi
                                     - dataInici
                                     - import
                                     - interessos
                                     - numDies
                                     - tipus
                                    type: object
                                    properties:
                                      dataFi:
                                        minLength: 1
                                        type: string
                                      dataInici:
                                        minLength: 1
                                        type: string
                                      import:
                                        minLength: 1
                                        type: string
                                      interessos:
                                        type: number
                                      numDies:
                                        type: number
                                      tipus:
                                        minLength: 1
                                        type: string
                x-examples:
                  example-1:
                    Envelope:
                      Body:
                        recalcularCalculResponse:
                          codError: 0
                          interessosExt:
                            GTH06_InteressosExt:
                              dataFi: 23/06/2021
                              dataInici: 23/05/2021
                              import: 1.000,00
                              interessos: 3.84
                              numDies: 32
                              tipus: 4,375
              examples:
                OK:
                  value:
                    Envelope:
                      Body:
                        recalcularCalculResponse:
                          codError: 0
                          interessosExt:
                            GTH06_InteressosExt:
                              dataFi: 23/06/2021
                              dataInici: 23/05/2021
                              import: 1.000,00
                              interessos: 3.84
                              numDies: 32
                              tipus: 4,375
      security:
       -
        default: []
      x-wso2-soap:
        soap-action: ""
        soap-operation: recalcularCalcul
        namespace: http://wsgaudi.e-tributs.net/GENTRI_WS
        x-soap-version: "1.1"
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  schemas: {}
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
   - x-atc-mocked
   - activityid
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://192.168.230.107:8080/gt_web/simuladorInteressosExt/GTWS06_SimInteressosExt.jws
  type: address
x-wso2-sandbox-endpoints:
  urls:
   - http://192.168.230.107:8080/gt_web/simuladorInteressosExt/GTWS06_SimInteressosExt.jws
  type: address
x-wso2-basePath: /gaudi/sim-interessos/v1
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
